export const PGZ_MSGS = {
  "PGZ__OPTIONAL CALLBACK NAME": "* Optional callback name",
  "PGZ__WHEN FINISHED EXECUTE THIS CODE": "* When finished, execute this code",
  "PGZ_ACTOR": "Actor",
  "PGZ_ADD A NEW GAME ACTOR": "Add a new game actor",
  "PGZ_ANIMATE OBJECT": "Animate object",
  "PGZ_ANIMATE THE ACTOR BY UPDATING ITS PROPERTIES PROGRESSIVELY": "Animate the actor by updating its properties progressively",
  "PGZ_CANCEL SCHEDULED CALLBACK": "Cancel scheduled callback",
  "PGZ_CANCEL THE GIVEN CALLBACK": "Cancel the given callback",
  "PGZ_CHANGE THE ACTOR TO ANOTHER IMAGE": "Change the actor to another image",
  "PGZ_CLEAR THE SCREEN": "Clear the screen",
  "PGZ_CREATE A RECTANGLE": "Create a rectangle",
  "PGZ_CREATE A RECTANGULAR SURFACE FOR USE IN PYGAME": "Create a rectangular surface for use in Pygame",
  "PGZ_DEFINE A NEW ACTOR IN THE GAME": "Define a new actor in the game",
  "PGZ_DEFINES A POSITION TARGET FOR ANIMATION": "Defines a position target for animation",
  "PGZ_DRAW LOOP": "Draw Loop",
  "PGZ_DRAW A LINE FROM": "Draw a line from",
  "PGZ_DRAW A(N)": "Draw a(n)",
  "PGZ_DRAW ACTOR": "Draw actor",
  "PGZ_DRAW IMAGE": "Draw image",
  "PGZ_DRAW TEXT": "Draw text",
  "PGZ_DRAW THE ACTOR ON THE SCREEN AT ITS SET POSITION": "Draw the actor on the screen at its set position",
  "PGZ_DRAWS A CIRCLE ON THE SCREEN": "Draws a circle on the screen",
  "PGZ_DRAWS A LINE ON THE SCREEN": "Draws a line on the screen",
  "PGZ_DRAWS A RECTANGLE ON THE SCREEN": "Draws a rectangle on the screen",
  "PGZ_DRAWS THE GIVEN IMAGE FILE ON THE SCREEN": "Draws the given image file on the screen",
  "PGZ_DRAWS THE GIVEN TEXT ON THE SCREEN USING FORMATTING": "Draws the given text on the screen using formatting",
  "PGZ_EXECUTE THE GIVEN CODE AFTER THE GIVEN DELAY (ONCE OR UNTIL CANCELLED)": "Execute the given code after the given delay (once or until cancelled)",
  "PGZ_EXECUTE THE GIVEN CODE AT THE GIVEN INTERVAL": "Execute the given code at the given interval",
  "PGZ_EXECUTES CODE WHEN A FINGER IS DRAGGED ACROSS THE TOUCHSCREEN": "Executes code when a finger is dragged across the touchscreen",
  "PGZ_EXECUTES CODE WHEN THE TOUCHSCREEN IS PRESSED OR RELEASED": "Executes code when the touchscreen is pressed or released",
  "PGZ_FILL SCREEN WITH": "Fill screen with",
  "PGZ_FILL THE SCREEN WITH THE GIVEN COLOR": "Fill the screen with the given color",
  "PGZ_FONT BACKGROUND COLOR": "Font background color",
  "PGZ_FONT COLOR": "Font color",
  "PGZ_FONT NAME": "Font name",
  "PGZ_FONT SIZE": "Font size",
  "PGZ_GET A COORDINATE PROPERTY VALUE FROM THE LAST TOUCH (INSIDE A TOUCHSCREEN EVENT HANDLER ONLY !)": "Get a coordinate property value from the last touch (inside a touchscreen event handler only !)",
  "PGZ_GET A PROPERTY VALUE FROM AN ACTOR": "Get a property value from an actor",
  "PGZ_GET DRAG DISTANCE": "Get drag distance",
  "PGZ_GET THE": "Get the",
  "PGZ_GET TOUCH POSITION": "Get touch position",
  "PGZ_HEIGHT": "Height",
  "PGZ_MAIN PYGAMEZERO DRAW LOOP": "Main Pygamezero Draw loop",
  "PGZ_MAIN PYGAMEZERO UPDATE LOOP": "Main Pygamezero Update Loop",
  "PGZ_MOVE ACTOR": "Move actor",
  "PGZ_MOVE THE CHARACTER TO A GIVEN POSITION USING A TUPLE": "Move the character to a given position using a tuple",
  "PGZ_MOVE THE CHARACTER TO A GIVEN POSITION": "Move the character to a given position",
  "PGZ_POSITION": "Position",
  "PGZ_REMOVES EVERYTHING OFF THE SCREEN": "Removes everything off the screen",
  "PGZ_RETURNS THE RELATIVE DISTANCE OF THE DRAG EVENT": "Returns the relative distance of the drag event (inside a drag event handler only !)",
  "PGZ_RETURNS THE TOUCH POSITION": "Returns the touch position (inside a touchscreen event handler only !)",
  "PGZ_RETURNS TRUE IF THE ACTOR IS COLLIDING WITH THE GIVEN POSITION": "Returns true if the actor is colliding with the given position",
  "PGZ_RETURNS TRUE IF THE ACTOR IS COLLIDING WITH THE GIVEN RECTANGLE": "Returns true if the actor is colliding with the given rectangle (can be another actor)",
  "PGZ_SCHEDULE": "Schedule",
  "PGZ_SET THE SCREEN'S WIDTH": "Set the screen's width",
  "PGZ_SETS A SHADOW UNDER THE TEXT WITH THE GIVEN OFFSET": "Sets a Shadow under the text with the given offset",
  "PGZ_SETS THE ALIGNMENT OF THE TEXT": "Sets the Alignment of the text",
  "PGZ_SETS THE FONT BACKGROUND COLOR OF THE TEXT": "Sets the Font Background Color of the text",
  "PGZ_SETS THE FONT COLOR OF THE TEXT": "Sets the Font Color of the text",
  "PGZ_SETS THE FONT NAME OF THE TEXT": "Sets the Font Name of the text",
  "PGZ_SETS THE FONT SIZE OF THE TEXT": "Sets the Font Size of the text",
  "PGZ_SETS THE ROTATION ANGLE OF THE TEXT": "Sets the Rotation Angle of the text",
  "PGZ_SETS THE POSITION ANCHOR OF THE TEXT": "Sets the Position anchor of the text",
  "PGZ_SETS THE SCREEN WIDTH AND HEIGHT": "Sets the screen width and height",
  "PGZ_TEXT ROTATION ANGLE": "Text Rotation Angle",
  "PGZ_TEXT ALIGNED TO THE ": "Text aligned to the ",
  "PGZ_TEXT POSITION ANCHORED BY ITS": "Text position anchored by its",
  "PGZ_TEXT SHADOW OFFSET BY ": "Text shadow offset by ",
  "PGZ_UPDATE LOOP": "Update Loop",
  "PGZ_UPDATE ACTOR": "Update actor",
  "PGZ_WHEN THE TOUCH SCREEN IS ": "When the touch screen is ",
  "PGZ_WHEN THE TOUCH SCREEN IS DRAGGED": "When the touch screen is dragged",
  "PGZ_WIDTH": "Width",
  "PGZ_X COORDINATE": "X coordinate",
  "PGZ_Y COORDINATE": "Y coordinate",
  "PGZ_X": "X",
  "PGZ_Y": "Y",
  "PGZ_ANCHORED BY ITS": "anchored by its",
  "PGZ_AND A RADIUS OF": "and a radius of",
  "PGZ_AND HEIGHT": "and height",
  "PGZ_AT X": "at X",
  "PGZ_AT POSITION X": "at position X",
  "PGZ_CIRCLE AT": "circle at",
  "PGZ_COLLIDING WITH POSITION": "colliding with position",
  "PGZ_COLLIDING WITH RECTANGLE OR ACTOR": "colliding with rectangle or actor",
  "PGZ_DURING": "during",
  "PGZ_EMPTY": "empty",
  "PGZ_FILLED": "filled",
  "PGZ_EVERY": "every",
  "PGZ_FORMATTED AS": "formatted as",
  "PGZ_IN COLOR": "in color",
  "PGZ_IN": "in",
  "PGZ_LEFT": "left",
  "PGZ_CENTER": "center",
  "PGZ_RIGHT": "right",
  "PGZ_LINEAR": "linear",
  "PGZ_ACCELERATE": "accelerate",
  "PGZ_DECELERATE": "decelerate",
  "PGZ_ACCELERATE THEN DECELERATE": "accelerate then decelerate",
  "PGZ_ELASTIC AT THE END": "elastic at the end",
  "PGZ_ELASTIC AT THE START": "elastic at the start",
  "PGZ_ELASTIC AT START AND END": "elastic at start and end",
  "PGZ_BOUNCE AT THE END": "bounce at the end",
  "PGZ_BOUNCE AT THE START": "bounce at the start",
  "PGZ_BOUNCE AT THE START AND END": "bounce at the start and end",
  "PGZ_OF THE TOUCH POSITION": "of the touch position",
  "PGZ_ON THE SCREEN AT POSITION": "on the screen at position",
  "PGZ_ONCE": "once",
  "PGZ_FOREVER": "forever",
  "PGZ_POSITION OF ACTOR": "position of actor",
  "PGZ_PRESSED": "pressed",
  "PGZ_RELEASED": "released",
  "PGZ_RECTANGLE ": "rectangle ",
  "PGZ_SECOND(S)": "second(s)",
  "PGZ_SECONDS": "seconds",
  "PGZ_TO POSITION X": "to position X",
  "PGZ_TO POSITION TUPLE": "to position tuple",
  "PGZ_TO": "to",
  "PGZ_TOP LEFT": "top left",
  "PGZ_MIDDLE TOP": "middle top",
  "PGZ_TOP RIGHT": "top right",
  "PGZ_MIDDLE LEFT": "middle left",
  "PGZ_MIDDLE RIGHT": "middle right",
  "PGZ_BOTTOM LEFT": "bottom left",
  "PGZ_MIDDLE BOTTOM": "middle bottom",
  "PGZ_BOTTOM RIGHT": "bottom right",
  "PGZ_USING TWEENING MODE": "using tweening mode",
  "PGZ_WITH IMAGE": "with image",
};
